<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.extensibility.execution" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DredgeAI.Core.TestBase\DredgeAI.Core.TestBase.csproj" />
    <ProjectReference Include="..\..\src\DredgeAI.Core.Domain\DredgeAI.Core.Domain.csproj" />
  </ItemGroup>

</Project>
