<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.BidCompare</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DredgeAI.BidCompare.Domain.Shared\DredgeAI.BidCompare.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\Core\src\DredgeAI.Core.Domain\DredgeAI.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.Domain" />
  </ItemGroup>

</Project>
