<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>380db47c-585a-48ba-abf4-8f036a6fae97</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Auth\src\DredgeAI.Auth.Host\DredgeAI.Auth.Host.csproj" />
      <ProjectReference Include="..\Base\src\DredgeAI.Base.Host\DredgeAI.Base.Host.csproj" />
      <ProjectReference Include="..\BidCompare\src\DredgeAI.BidCompare.Host\DredgeAI.BidCompare.Host.csproj" />
      <ProjectReference Include="..\Gateway\DredgeAI.Gateway.Host\DredgeAI.Gateway.Host.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Docker" />
    </ItemGroup>


</Project>
