<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.Gateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.extensibility.execution" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DredgeAI.Gateway.Domain\DredgeAI.Gateway.Domain.csproj" />
    <ProjectReference Include="..\DredgeAI.Gateway.TestBase\DredgeAI.Gateway.TestBase.csproj" />
  </ItemGroup>

</Project>
