<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.Gateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DredgeAI.Gateway.Domain.Shared\DredgeAI.Gateway.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

</Project>
