// <auto-generated />
using System;
using DredgeAI.BidCompare.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace DredgeAI.BidCompare.Migrations
{
    [DbContext(typeof(BidCompareDbContext))]
    [Migration("20260826060555_Add_init_tables")]
    partial class Add_init_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DredgeAI.BidCompare.AI.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("f_attempts")
                        .HasComment("调用尝试次数（含重试）");

                    b.Property<string>("Business")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_business")
                        .HasComment("业务场景标识");

                    b.Property<string>("CircuitBreakerState")
                        .HasColumnType("text")
                        .HasColumnName("f_circuit_breaker_state")
                        .HasComment("熔断器状态");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_error_message")
                        .HasComment("错误信息");

                    b.Property<string>("ErrorType")
                        .HasColumnType("text")
                        .HasColumnName("f_error_type")
                        .HasComment("错误类型");

                    b.Property<string>("FinishReason")
                        .HasColumnType("text")
                        .HasColumnName("f_finish_reason")
                        .HasComment("模型结束原因");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("f_input_tokens")
                        .HasComment("输入 token 数");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<double?>("LatencySeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("f_latency_seconds")
                        .HasComment("调用耗时（秒）");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("f_output_tokens")
                        .HasComment("输出 token 数");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("f_success")
                        .HasComment("是否成功");

                    b.Property<string>("TextPreview")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_text_preview")
                        .HasComment("输入文本预览");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("f_total_tokens")
                        .HasComment("总 token 数");

                    b.Property<string>("UsedConfig")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_used_config")
                        .HasComment("使用的模型配置名");

                    b.Property<string>("UsedModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_used_model")
                        .HasComment("实际调用模型名");

                    b.HasKey("Id");

                    b.HasIndex("Business");

                    b.HasIndex("CreationTime");

                    b.HasIndex("UsedConfig");

                    b.HasIndex("Success", "CreationTime");

                    b.ToTable("tab_ai_usage_record", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.Clauses.ClauseTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_category")
                        .HasComment("分类");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("f_mandatory")
                        .HasComment("是否强制条款");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("f_text")
                        .HasComment("条款文本");

                    b.HasKey("Id");

                    b.ToTable("tab_clause_template", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.CompareTasks.CompareTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<bool>("AutoCompareOnParseComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("f_auto_compare_on_parse_complete")
                        .HasComment("解析完成后是否自动进入两两对比");

                    b.Property<string>("ClauseDraftsJson")
                        .HasColumnType("text")
                        .HasColumnName("f_clause_drafts_json")
                        .HasComment("条款提取草案 JSON，确认前可反复重抽覆盖，确认后转 ClauseSnapshotJson");

                    b.Property<string>("ClauseSnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("f_clause_snapshot_json")
                        .HasComment("条款清单快照 JSON（元素见 ClauseSnapshotItem），锁定后不可变");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_failure_reason")
                        .HasComment("Partial/Failed 的原因说明");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_name")
                        .HasComment("任务名称（项目名）");

                    b.Property<bool>("NameEditedByUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_name_edited_by_user")
                        .HasComment("用户是否手动编辑过项目名；true 后前端轮询不再自动应用 SuggestedName");

                    b.Property<string>("PairsJson")
                        .HasColumnType("text")
                        .HasColumnName("f_pairs_json")
                        .HasComment("两两对比对清单 JSON（元素见 ComparePairItem）");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("f_progress_message")
                        .HasComment("进度提示消息");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("f_progress_percent")
                        .HasComment("进度百分比 0~100");

                    b.Property<string>("ProgressStage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("f_progress_stage")
                        .HasComment("当前进度阶段标识（如 parsing/comparing）");

                    b.Property<DateTime?>("ReportGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_report_generated_at")
                        .HasComment("报告生成时间");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text")
                        .HasColumnName("f_report_json")
                        .HasComment("报告 JSON 缓存（CompareReportDto 序列化），任务 Done 后生成");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("任务状态（CompareTaskStatus 状态机）");

                    b.Property<string>("SuggestedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_suggested_name")
                        .HasComment("解析完成后由后端推断的项目名建议");

                    b.Property<Guid?>("TenderDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_tender_document_id")
                        .HasComment("招标文件文档 ID（CompareDocument.Role=Tender）");

                    b.Property<Guid?>("TenderReadingTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_tender_reading_task_id")
                        .HasComment("来源读标任务 ID（创建比标任务时引用读标基准库）");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("tab_compare_task", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.Documents.CompareDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("AnGineerDocId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_an_gineer_doc_id")
                        .HasComment("AnGineer 侧文档 id（恢复解析复用，重解析不清空）");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("DocMdStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_doc_md_storage_key")
                        .HasComment("content.md 对象存储 key（AnGineer 阅读流 Markdown，LLM 语义层用）");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("f_file_extension")
                        .HasComment("文件扩展名（如 .pdf）");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_file_name")
                        .HasComment("原始文件名");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("f_file_size")
                        .HasComment("文件大小（字节）");

                    b.Property<string>("IrStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_ir_storage_key")
                        .HasComment("内部适配 IR 对象存储 key：compare/{taskId}/{docId}/ir.json");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<double?>("OcrLowConfidenceRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("f_ocr_low_confidence_ratio")
                        .HasComment("OCR 低置信块占比（source=ocr 且 confidence<0.5）");

                    b.Property<string>("OriginStorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_origin_storage_key")
                        .HasComment("原始文件对象存储 key：compare/{taskId}/{docId}/origin.{ext}");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("f_page_count")
                        .HasComment("页数");

                    b.Property<string>("ParseError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_parse_error")
                        .HasComment("解析失败原因");

                    b.Property<DateTime?>("ParseFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_parse_finished_at")
                        .HasComment("本次解析结束时间（成功/失败均记录）");

                    b.Property<int?>("ParseProgress")
                        .HasColumnType("integer")
                        .HasColumnName("f_parse_progress")
                        .HasComment("AnGineer 解析进度 0~100，终态为 100");

                    b.Property<string>("ParseStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_parse_stage")
                        .HasComment("AnGineer 当前管线阶段（source_prep/convert/raw_parse/...）");

                    b.Property<string>("ParseStageMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("f_parse_stage_message")
                        .HasComment("AnGineer 当前阶段消息");

                    b.Property<DateTime?>("ParseStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_parse_started_at")
                        .HasComment("本次解析开始时间");

                    b.Property<byte>("ParseStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("f_parse_status")
                        .HasComment("解析状态（DocumentParseStatus）");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("f_role")
                        .HasComment("文档角色（Bid=投标书 Tender=招标文件）");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_task_id")
                        .HasComment("所属比标任务 ID");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("tab_compare_document", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.Drafts.CompareDraftDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_draft_id")
                        .HasComment("上传会话 ID（前端生成 UUID，不属于任务记录）");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("f_file_extension")
                        .HasComment("文件扩展名");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_file_name")
                        .HasComment("原始文件名");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("f_file_size")
                        .HasComment("文件大小（字节）");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("OriginStorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_origin_storage_key")
                        .HasComment("原始文件对象存储 key：compare/drafts/{draftId}/{docId}/origin.{ext}");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("f_role")
                        .HasComment("文档角色（Bid/Tender）");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.ToTable("tab_compare_draft_document", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.Evidences.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<bool>("AiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("f_ai_generated")
                        .HasComment("是否 AI 生成结论（与算法证据在 UI 上区分）");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("f_description")
                        .HasComment("证据描述");

                    b.Property<string>("DocIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_doc_ids_json")
                        .HasComment("涉及文档 ID 列表 JSON 数组");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("LocationsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_locations_json")
                        .HasComment("定位信息 JSON：{ docId, blockIds[] }[]");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("text")
                        .HasColumnName("f_metrics_json")
                        .HasComment("指标 JSON（如 similarity）");

                    b.Property<byte>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("f_severity")
                        .HasComment("严重级别（High/Mid/Low）");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_task_id")
                        .HasComment("所属比标任务 ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_title")
                        .HasComment("证据标题");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("f_type")
                        .HasComment("证据类型（Similarity/Pricing/Metadata/Clause/Indicator）");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Severity");

                    b.HasIndex("TaskId", "Type");

                    b.ToTable("tab_evidence_item", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.Exports.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_error")
                        .HasComment("失败原因（导出失败可重试）");

                    b.Property<string>("FileStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_file_storage_key")
                        .HasComment("导出文件对象存储 key：compare/{taskId}/exports/{jobId}.{pdf|docx}");

                    b.Property<byte>("Format")
                        .HasColumnType("smallint")
                        .HasColumnName("f_format")
                        .HasComment("导出格式（Pdf/Word）");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("导出任务状态");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_task_id")
                        .HasComment("所属比标任务 ID");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("tab_export_job", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("Bbox")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_bbox")
                        .HasComment("人脸框 [x1,y1,x2,y2] JSON，未识别人脸去重用，无坐标为 \"[]\"");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("f_confidence")
                        .HasComment("人脸识别置信度");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<Guid>("MeetingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_meeting_record_id")
                        .HasComment("所属会议记录 ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_name")
                        .HasComment("姓名（未识别为空串）");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("出勤状态（Present/Absent/Late/Unrecognized）");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_team")
                        .HasComment("班组");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_worker_id")
                        .HasComment("识别到的工人 ID，未识别为 null");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecordId");

                    b.HasIndex("MeetingRecordId", "WorkerId");

                    b.ToTable("tab_attendance_record", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.MeetingProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("AnGineerDocId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_an_gineer_doc_id")
                        .HasComment("AnGineer 解析产物 doc id（知识库检索用）");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("DocIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_doc_ids_json")
                        .HasComment("全部施工方案解析产物 doc id 列表 JSON");

                    b.Property<string>("DocNamesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_doc_names_json")
                        .HasComment("与 DocIdsJson 对齐的原始文件名列表 JSON（编辑抽屉展示）");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_name")
                        .HasComment("项目名称");

                    b.Property<string>("ProjectInfoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_project_info_json")
                        .HasComment("LLM 提取的项目信息 JSON");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("f_status")
                        .HasComment("解析状态：processing / ready / failed");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_summary")
                        .HasComment("LLM 提取的施工方案主要内容");

                    b.HasKey("Id");

                    b.ToTable("tab_meeting_project", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.MeetingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_date")
                        .HasComment("会议日期");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_ended_at")
                        .HasComment("会议结束时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("PreInfoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_pre_info_json")
                        .HasComment("会前信息 JSON（晨会稿素材）");

                    b.Property<string>("ReportError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_report_error")
                        .HasComment("报告生成失败原因");

                    b.Property<string>("ReportFile")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_report_file")
                        .HasComment("Markdown 报告存储 key");

                    b.Property<Guid?>("SpeechDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_speech_draft_id")
                        .HasComment("关联晨会稿 ID");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_started_at")
                        .HasComment("会议开始时间");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("会议状态（MeetingStatus）");

                    b.Property<string>("TranscriptFile")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_transcript_file")
                        .HasComment("会议全程录音存储 key（IFileStorage）");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("text")
                        .HasColumnName("f_transcript_text")
                        .HasComment("转写文本（后台任务回填）");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.ToTable("tab_meeting_record", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.QaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_answer")
                        .HasComment("回答内容");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_created_at")
                        .HasComment("提问时间");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<byte>("IntentType")
                        .HasColumnType("smallint")
                        .HasColumnName("f_intent_type")
                        .HasComment("意图类型（Knowledge/Chitchat/Meeting）");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<Guid>("MeetingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_meeting_record_id")
                        .HasComment("所属会议记录 ID");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_question")
                        .HasComment("提问内容");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_sources_json")
                        .HasComment("证据来源（文件名/页码 JSON 数组）");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecordId");

                    b.ToTable("tab_qa_record", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.SpeechDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_content")
                        .HasComment("稿件内容");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<Guid>("MeetingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_meeting_record_id")
                        .HasComment("所属会议记录 ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("f_status")
                        .HasComment("草稿状态（draft/generated/confirmed）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_updated_at")
                        .HasComment("草稿最后更新时间");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecordId")
                        .IsUnique()
                        .HasFilter("f_is_deleted = false");

                    b.ToTable("tab_speech_draft", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.UnrecognizedFace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("BboxJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_bbox_json")
                        .HasComment("人脸框 [x1,y1,x2,y2] JSON");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("f_confidence")
                        .HasComment("识别置信度");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<Guid>("MeetingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_meeting_record_id")
                        .HasComment("所属会议记录 ID");

                    b.Property<string>("PhotoKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_photo_key")
                        .HasComment("裁剪图存储 key（IFileStorage）");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecordId");

                    b.ToTable("tab_unrecognized_face", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.MeetingBot.WorkerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("f_employee_no")
                        .HasComment("工号（业务唯一）");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<DateTime?>("FaceEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_face_enrolled_at")
                        .HasComment("人脸录入时间");

                    b.Property<string>("FacePhotosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_face_photos_json")
                        .HasComment("人脸照片存储 key JSON 数组");

                    b.Property<byte>("FaceStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("f_face_status")
                        .HasComment("人脸录入状态（Pending/Enrolled）");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_name")
                        .HasComment("工人姓名");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_team")
                        .HasComment("班组");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasFilter("f_is_deleted = false");

                    b.ToTable("tab_worker_profile", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.TenderReadings.BaselineField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("f_category")
                        .HasComment("字段分类（BaselineCategory：项目信息/商务数据/目录树等）");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("f_confidence")
                        .HasComment("置信度 0~1");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Extractor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("f_extractor")
                        .HasComment("来源抽取器：rule / llm / rule+llm");

                    b.Property<string>("ExtractorVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("f_extractor_version")
                        .HasComment("抽取器版本");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_field_key")
                        .HasComment("业务字段名，如 price_ceiling");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_raw_text")
                        .HasComment("原文摘要");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("字段状态（Auto/NeedsReview/Confirmed/Edited）");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_task_id")
                        .HasComment("所属读标任务 ID");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_value_json")
                        .HasComment("结构化值 JSON");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Category");

                    b.HasIndex("TaskId", "FieldKey");

                    b.ToTable("tab_baseline_field", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.TenderReadings.SourceMapItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("BboxJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_bbox_json")
                        .HasComment("0~1 归一化矩形 [x0,y0,x1,y1] JSON 数组字符串");

                    b.Property<string>("BlockId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_block_id")
                        .HasComment("AnGineer block_uid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_field_id")
                        .HasComment("所属基准库字段 ID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<int>("PageIdx")
                        .HasColumnType("integer")
                        .HasColumnName("f_page_idx")
                        .HasComment("0 基页码，与 IR 一致");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_text")
                        .HasComment("原文片段");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldId", "PageIdx");

                    b.ToTable("tab_source_map_item", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.TenderReadings.TenderReadingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("AnGineerDocId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_an_gineer_doc_id")
                        .HasComment("AnGineer 侧文档 id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("DocMdStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_doc_md_storage_key")
                        .HasComment("content.md 对象存储 key");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("f_file_extension")
                        .HasComment("文件扩展名");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_file_name")
                        .HasComment("原始文件名");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("f_file_size")
                        .HasComment("文件大小（字节）");

                    b.Property<string>("IrStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_ir_storage_key")
                        .HasComment("内部适配 IR 对象存储 key");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("OriginStorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_origin_storage_key")
                        .HasComment("原始文件对象存储 key");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("f_page_count")
                        .HasComment("页数");

                    b.Property<string>("ParseError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_parse_error")
                        .HasComment("解析失败原因");

                    b.Property<DateTime?>("ParseFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_parse_finished_at")
                        .HasComment("本次解析结束时间");

                    b.Property<int?>("ParseProgress")
                        .HasColumnType("integer")
                        .HasColumnName("f_parse_progress")
                        .HasComment("AnGineer 解析进度 0~100");

                    b.Property<string>("ParseStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_parse_stage")
                        .HasComment("AnGineer 当前管线阶段");

                    b.Property<string>("ParseStageMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("f_parse_stage_message")
                        .HasComment("AnGineer 当前阶段消息");

                    b.Property<DateTime?>("ParseStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_parse_started_at")
                        .HasComment("本次解析开始时间");

                    b.Property<byte>("ParseStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("f_parse_status")
                        .HasComment("解析状态（DocumentParseStatus）");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_task_id")
                        .HasComment("所属读标任务 ID");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("tab_tender_reading_document", (string)null);
                });

            modelBuilder.Entity("DredgeAI.BidCompare.TenderReadings.TenderReadingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("f_failure_reason")
                        .HasComment("失败原因");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_name")
                        .HasComment("任务名称");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("f_progress_percent")
                        .HasComment("进度百分比 0~100");

                    b.Property<string>("ProgressStage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("f_progress_stage")
                        .HasComment("当前进度阶段标识");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_project_code")
                        .HasComment("项目编号（如 ZB-2026-008），抽取后回填");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("f_status")
                        .HasComment("读标任务状态");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("Status");

                    b.ToTable("tab_tender_reading_task", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.BackgroundJobs.BackgroundJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("f_application_name")
                        .HasComment("应用名称");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsAbandoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_abandoned")
                        .HasComment("是否不再运行");

                    b.Property<string>("JobArgs")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("character varying(1048576)")
                        .HasColumnName("f_job_args")
                        .HasComment("任务参数");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_job_name")
                        .HasComment("任务名");

                    b.Property<DateTime?>("LastTryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_try_time")
                        .HasComment("最后一次尝试时间");

                    b.Property<DateTime>("NextTryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_next_try_time")
                        .HasComment("下一次尝试时间");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)15)
                        .HasColumnName("f_priority")
                        .HasComment("权重");

                    b.Property<short>("TryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("f_try_count")
                        .HasComment("尝试次数");

                    b.HasKey("Id");

                    b.HasIndex("JobName");

                    b.HasIndex("IsAbandoned", "NextTryTime");

                    b.ToTable("tab_background_jobs", null, t =>
                        {
                            t.HasComment("后台任务记录表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
