/**
 * URL 契约：所有 API 资源路径在此声明，双端共用同一 key。
 * 路径不含 baseURL 前缀（前缀由各端的 createRequest 注入）。
 * 修复历史问题：原 user-web 用 /key、admin-web 用 /apikey，命名不统一。
 */
export const urls = {
  // user-web
  userCurrent: '/user/current',
  appList: '/app/list',
  taskRecent: '/task/recent',
  taskQuick: '/task/quick',
  fileRecent: '/file/recent',
  bidSessions: '/bid/sessions',
  standardResult: '/standard/result',
  standardHistory: '/standard/history',
  standardCategories: '/standard/categories',
  standardRecommended: '/standard/recommended',
  standardList: '/standard/list',
  standardProperty: '/standard/property',
  standardPropertyList: '/standard/property/list',
  standardDocument: '/standard/document',
  standardAIAnalysis: '/standard/ai-analysis',
  standardRecords: '/standard/records',
  standardRecordsTree: '/standard/records/tree',
  standardRecord: '/standard/records/:id',
  standardRecordFiles: '/standard/records/:id/files',
  standardRecordFileContent: '/standard/records/:id/files/:fileId/content',
  standardQaAsk: '/standard/qa/ask',
  chartEfficiencyTrend: '/chart/efficiency-trend',

  // 共享（双端均使用 /apikey 命名，统一规范）
  apiKeyList: '/apikey/list',
  apiKeyModels: '/apikey/models',
  apiKeyUsageByModel: '/apikey/usage-by-model',
  apiKeyUsageByKey: '/apikey/usage-by-key',
  apiKeyUsageStats: '/apikey/usage-stats',
  apiKeyUsageTimeSeries: '/apikey/usage-timeseries',
  apiKeyRecords: '/apikey/records',

  // AI 配音（直连 CosyVoice TTS 服务，经 Vite /tts 代理转发到 localhost:8000）
  dubbingVoices: '/tts/voices',
  dubbingGenerate: '/tts/tts',
  dubbingRegister: '/tts/voices/upload',
  adminVoices: '/dubbing/admin/voices',
  dubbingTasks: '/dubbing/tasks',
  dubbingTask: '/dubbing/tasks/:id',
  dubbingTaskDownload: '/dubbing/tasks/:id/download',
  adminDubbingTasks: '/dubbing/admin/tasks',
  adminDubbingTask: '/dubbing/admin/tasks/:id',
  adminDubbingUsageSummary: '/dubbing/admin/usage/summary',
  adminDubbingUsageTimeseries: '/dubbing/admin/usage/timeseries',

  // AI 比标
  compareTasks: '/compare/tasks',
  compareTask: '/compare/tasks/:id',
  compareTaskDocuments: '/compare/tasks/:id/documents',
  compareTaskStartParse: '/compare/tasks/:id/documents/parse',
  compareTaskDocumentFile: '/compare/tasks/:id/documents/:docId/file',
  compareTaskReparse: '/compare/tasks/:id/documents/reparse',
  compareTaskCompareRetry: '/compare/tasks/:id/compare/retry',
  compareTaskAiRetry: '/compare/tasks/:id/ai/retry',
  compareTaskName: '/compare/tasks/:id/name',
  compareTaskIr: '/compare/tasks/:id/ir/:docId',
  compareTaskEvidences: '/compare/tasks/:id/evidences',
  compareTaskMatrix: '/compare/tasks/:id/matrix',
  compareTaskClauses: '/compare/tasks/:id/clauses',
  compareTaskClauseExtract: '/compare/tasks/:id/clauses/extract',
  compareTaskExport: '/compare/tasks/:id/export',
  compareTaskExportStatus: '/compare/tasks/:id/exports/:exportId',
  // 上传会话（选中即上传，仅暂存文件，不建任务）
  compareDraft: '/compare/drafts/:draftId',
  compareDraftDocuments: '/compare/drafts/:draftId/documents',
  compareDraftDocument: '/compare/drafts/:draftId/documents/:docId',

  // AI 读标
  tenderReadTasks: '/tender-read/tasks',
  tenderReadTask: '/tender-read/tasks/:id',
  tenderReadTaskName: '/tender-read/tasks/:id/name',
  tenderReadTaskDocuments: '/tender-read/tasks/:id/documents',
  tenderReadTaskDocument: '/tender-read/tasks/:id/document',
  tenderReadTaskParse: '/tender-read/tasks/:id/parse',
  tenderReadTaskReparse: '/tender-read/tasks/:id/reparse',
  tenderReadTaskOutline: '/tender-read/tasks/:id/outline',
  tenderReadTaskParsedDocument: '/tender-read/tasks/:id/document/parsed',
  tenderReadTaskBaseline: '/tender-read/tasks/:id/baseline',
  tenderReadTaskField: '/tender-read/tasks/:id/fields/:fieldId',
  tenderReadTaskReExtract: '/tender-read/tasks/:id/re-extract',
  tenderReadTaskDocumentFile: '/tender-read/tasks/:id/document/file',
  tenderReadTaskExport: '/tender-read/tasks/:id/export',

  // admin-web
  adminStats: '/dashboard/stats',
  dashboardMetrics: '/dashboard/metrics',
  dashboardApiCallsTrend: '/dashboard/api-calls-trend',
  dashboardAppDistribution: '/dashboard/app-distribution',
  dashboardActiveUsersTrend: '/dashboard/active-users-trend',
  dashboardRecentLogs: '/dashboard/recent-logs',
  analyticsDailyApiCalls: '/analytics/daily-api-calls',
  analyticsModelUsage: '/analytics/model-usage',
  analyticsUserGrowth: '/analytics/user-growth',
  analyticsErrorRate: '/analytics/error-rate',
  applications: '/applications',
  adminAppOrder: '/app-order',
  adminAppOrderSeed: '/app-order/seed',
  adminAppOrderMove: '/app-order/move',
  adminAppOrderReset: '/app-order/reset',
  userAppOrder: '/admin/app-order/user',
  userAppDefaultOrder: '/admin/app-order',
  permissions: '/permissions',
  orgUsers: '/org-users',
  orgUserStatus: '/org-users/:id/status',
  orgUserRoles: '/org-users/:id/roles',
  roles: '/roles',
  roleDetail: '/roles/:id',
  roleUsers: '/roles/:id/users',
  rolePermissions: '/roles/:id/permissions',
  datasources: '/datasources',
  adminProfile: '/profile',

  // 知识库-标准规范（admin-web）
  adminStandards: '/standards',
  adminStandardUpdate: '/standards/:id',
  adminStandardDelete: '/standards/:id',
  adminStandardParse: '/standards/:id/parse',
  adminStandardCreate: '/standards',
  adminStandardPreview: '/standards/preview',
  adminStandardsBatchDelete: '/standards/batch-delete',
  adminStandardsBatchParse: '/standards/batch-parse',
  adminStandardEnabled: '/standards/:id/enabled',
  adminStandardSyncStatus: '/standards/sync-status',

  // AI 晨会
  meetingRecord: '/meeting/records',
  meetingHistory: '/meeting/records',
  meetingParsePlan: '/meeting/parse-plan',
  meetingSpeechGenerate: '/meeting/records/:id/speech/generate',
  meetingSpeechDraft: '/meeting/records/:id/speech',
  meetingSpeechAudio: '/meeting/records/:id/speech/audio',
  meetingSpeechAudioStatus: '/meeting/records/:id/speech/audio/status',
  meetingSpeechLeadAudio: '/meeting/records/:id/speech/audio/lead',
  meetingSpeechSegmentAudio: '/meeting/records/:id/speech/audio/segment/:index',
  meetingSpeechAudioCache: '/meeting/records/:id/speech/audio/cache',
  meetingAsr: '/meeting/asr',
  meetingTts: '/meeting/tts',
  meetingKnowledgeDocuments: '/meeting/knowledge/documents',
  meetingKnowledgeDocumentStatus: '/meeting/knowledge/documents/:docId/status',
  meetingStart: '/meeting/records/:id/start',
  meetingAttendanceRecognize: '/meeting/records/:id/attendance/recognize',
  meetingUnrecognizedFaces: '/meeting/records/:id/unrecognized-faces',
  meetingAttendance: '/meeting/records/:id/attendance',
  meetingQa: '/meeting/records/:id/qa',
  meetingQaAudio: '/meeting/records/:id/qa/audio',
  meetingQaAudioGet: '/meeting/qa/:qaId/audio',
  meetingRecording: '/meeting/records/:id/recording',
  meetingComplete: '/meeting/records/:id/complete',
  meetingReport: '/meeting/records/:id/report',
  meetingWorkers: '/meeting/workers',
  meetingWorkerFace: '/meeting/workers/:id/face',
  meetingWorkersRecognizeIdCard: '/meeting/workers/recognize-id-card',
  meetingProjects: '/meeting/projects',
  meetingProject: '/meeting/projects/:id',
  meetingProjectExtract: '/meeting/projects/:id/extract',
  meetingProjectSuggestName: '/meeting/projects/suggest-name',
  meetingProjectDocumentFile: '/meeting/projects/:id/documents/:docId/file',
  meetingProjectDocumentContent: '/meeting/projects/:id/documents/:docId/content',
} as const

export type UrlKey = keyof typeof urls
