/**
 * URL 契约：所有 API 资源路径在此声明，双端共用同一 key。
 * 路径不含 baseURL 前缀（前缀由各端的 createRequest 注入）。
 * 修复历史问题：原 user-web 用 /key、admin-web 用 /apikey，命名不统一。
 */
export const urls = {
  // 认证（/connect 前缀，不经 API baseURL，由 auth 模块直接用 fetch 拼同源路径）
  authToken: '/connect/token',
  authAuthorize: '/connect/authorize',

  // user-web
  userCurrent: '/user/current',
  appList: '/bidcompare/app-catalog/list',
  taskRecent: '/task/recent',
  taskQuick: '/task/quick',
  fileRecent: '/file/recent',
  bidSessions: '/bid/sessions',
  standardResult: '/standard/result',
  standardHistory: '/standard/history',
  standardCategories: '/standard/categories',
  standardRecommended: '/standard/recommended',
  standardList: '/standard/list',
  standardProperty: '/standard/property',
  standardPropertyList: '/standard/property/list',
  standardDocument: '/standard/document',
  standardAIAnalysis: '/standard/ai-analysis',
  standardRecords: '/standard/records',
  standardRecordsTree: '/standard/records/tree',
  standardRecord: '/standard/records/:id',
  standardRecordFiles: '/standard/records/:id/files',
  standardRecordFileContent: '/standard/records/:id/files/:fileId/content',
  standardQaAsk: '/standard/qa/ask',
  chartEfficiencyTrend: '/chart/efficiency-trend',

  // 共享（双端均使用 /apikey 命名，统一规范）
  apiKeyList: '/bidcompare/apikey/list',
  apiKeyModels: '/bidcompare/apikey/models',
  apiKeyUsageByModel: '/bidcompare/apikey/usage-by-model',
  apiKeyUsageByKey: '/bidcompare/apikey/usage-by-key',
  apiKeyUsageStats: '/bidcompare/apikey/usage-stats',
  apiKeyUsageTimeSeries: '/bidcompare/apikey/usage-timeseries',
  apiKeyRecords: '/bidcompare/apikey/records',

  // AI 配音（直连 CosyVoice TTS 服务，经 Vite /tts 代理转发到 localhost:8000）
  dubbingVoices: '/tts/voices',
  dubbingGenerate: '/tts/tts',
  dubbingRegister: '/tts/voices/upload',
  adminVoices: '/dubbing/admin/voices',
  dubbingTasks: '/dubbing/tasks',
  dubbingTask: '/dubbing/tasks/:id',
  dubbingTaskDownload: '/dubbing/tasks/:id/download',
  adminDubbingTasks: '/dubbing/admin/tasks',
  adminDubbingTask: '/dubbing/admin/tasks/:id',
  adminDubbingUsageSummary: '/dubbing/admin/usage/summary',
  adminDubbingUsageTimeseries: '/dubbing/admin/usage/timeseries',

  // AI 比标
  compareTasks: '/bidcompare/compare-tasks',
  compareTask: '/bidcompare/compare-tasks/:id',
  compareTaskDocuments: '/bidcompare/compare-tasks/:id/documents',
  compareTaskStartParse: '/bidcompare/compare-tasks/:id/documents/parse',
  compareTaskDocumentFile: '/bidcompare/compare-tasks/:id/documents/:docId/file',
  compareTaskReparse: '/bidcompare/compare-tasks/:id/documents/reparse',
  compareTaskCompareRetry: '/bidcompare/compare-tasks/:id/compare/retry',
  compareTaskAiRetry: '/bidcompare/compare-tasks/:id/ai/retry',
  compareTaskName: '/bidcompare/compare-tasks/:id/name',
  compareTaskIr: '/bidcompare/compare-tasks/:id/documents/:docId/ir',
  compareTaskEvidences: '/bidcompare/compare-tasks/:id/evidences',
  compareTaskMatrix: '/bidcompare/compare-tasks/:id/matrix',
  compareTaskClauses: '/bidcompare/compare-tasks/:id/clauses',
  compareTaskClauseExtract: '/bidcompare/compare-tasks/:id/clauses/extract',
  compareTaskExport: '/bidcompare/compare-tasks/:id/export',
  compareTaskExportStatus: '/bidcompare/compare-tasks/:id/exports/:exportId',
  // 上传会话（选中即上传，仅暂存文件，不建任务）
  compareDraft: '/bidcompare/compare-drafts/:draftId',
  compareDraftDocuments: '/bidcompare/compare-drafts/:draftId/documents',
  compareDraftDocument: '/bidcompare/compare-drafts/:draftId/documents/:docId',

  // AI 读标
  tenderReadTasks: '/bidcompare/tender-reading-tasks',
  tenderReadTask: '/bidcompare/tender-reading-tasks/:id',
  tenderReadTaskName: '/bidcompare/tender-reading-tasks/:id/name',
  tenderReadTaskDocuments: '/bidcompare/tender-reading-tasks/:id/documents',
  tenderReadTaskDocument: '/bidcompare/tender-reading-tasks/:id/document',
  tenderReadTaskParse: '/bidcompare/tender-reading-tasks/:id/parse',
  tenderReadTaskReparse: '/bidcompare/tender-reading-tasks/:id/reparse',
  tenderReadTaskOutline: '/bidcompare/tender-reading-tasks/:id/outline',
  tenderReadTaskParsedDocument: '/bidcompare/tender-reading-tasks/:id/document/parsed',
  tenderReadTaskBaseline: '/bidcompare/tender-reading-tasks/:id/baseline',
  tenderReadTaskField: '/bidcompare/tender-reading-tasks/:id/fields/:fieldId',
  tenderReadTaskReExtract: '/bidcompare/tender-reading-tasks/:id/re-extract',
  tenderReadTaskDocumentFile: '/bidcompare/tender-reading-tasks/:id/document/file',
  tenderReadTaskExport: '/bidcompare/tender-reading-tasks/:id/export',

  // admin-web
  adminStats: '/dashboard/stats',
  dashboardMetrics: '/dashboard/metrics',
  dashboardApiCallsTrend: '/dashboard/api-calls-trend',
  dashboardAppDistribution: '/dashboard/app-distribution',
  dashboardActiveUsersTrend: '/dashboard/active-users-trend',
  dashboardRecentLogs: '/dashboard/recent-logs',
  analyticsDailyApiCalls: '/analytics/daily-api-calls',
  analyticsModelUsage: '/analytics/model-usage',
  analyticsUserGrowth: '/analytics/user-growth',
  analyticsErrorRate: '/analytics/error-rate',
  applications: '/bidcompare/app-catalog',
  adminAppOrder: '/bidcompare/app-order',
  adminAppOrderSeed: '/bidcompare/app-order/seed',
  adminAppOrderMove: '/bidcompare/app-order/move',
  adminAppOrderReset: '/bidcompare/app-order/reset',
  userAppOrder: '/bidcompare/app-order/user',
  userAppDefaultOrder: '/bidcompare/app-order/user',
  permissions: '/permissions',
  orgUsers: '/org-users',
  orgUserStatus: '/org-users/:id/status',
  orgUserRoles: '/org-users/:id/roles',
  roles: '/roles',
  roleDetail: '/roles/:id',
  roleUsers: '/roles/:id/users',
  rolePermissions: '/roles/:id/permissions',
  datasources: '/datasources',
  adminProfile: '/profile',

  // 知识库-标准规范（admin-web）
  adminStandards: '/standards',
  adminStandardUpdate: '/standards/:id',
  adminStandardDelete: '/standards/:id',
  adminStandardParse: '/standards/:id/parse',
  adminStandardCreate: '/standards',
  adminStandardPreview: '/standards/preview',
  adminStandardsBatchDelete: '/standards/batch-delete',
  adminStandardsBatchParse: '/standards/batch-parse',
  adminStandardEnabled: '/standards/:id/enabled',
  adminStandardSyncStatus: '/standards/sync-status',

  // AI 晨会
  meetingRecord: '/bidcompare/meeting-records',
  meetingHistory: '/bidcompare/meeting-records',
  meetingParsePlan: '/bidcompare/meeting-records/parse-plan',
  meetingSpeechGenerate: '/bidcompare/meeting-records/:id/speech/generate',
  meetingSpeechGenerateStream: '/bidcompare/meeting-records/:id/speech/generate/stream',
  meetingSpeechDraft: '/bidcompare/meeting-records/:id/speech',
  meetingSpeechAudio: '/bidcompare/meeting-records/:id/speech/audio',
  meetingSpeechAudioStatus: '/bidcompare/meeting-records/:id/speech/audio/status',
  meetingSpeechLeadAudio: '/bidcompare/meeting-records/:id/speech/audio/lead',
  meetingSpeechSegmentAudio: '/bidcompare/meeting-records/:id/speech/audio/segment/:index',
  meetingSpeechAudioCache: '/bidcompare/meeting-records/:id/speech/audio/cache',
  meetingAsr: '/bidcompare/meeting-records/asr',
  meetingTts: '/bidcompare/meeting-records/tts',
  meetingKnowledgeDocuments: '/bidcompare/knowledge-documents',
  meetingKnowledgeDocumentStatus: '/bidcompare/knowledge-documents/:docId/status',
  meetingStart: '/bidcompare/meeting-records/:id/start',
  meetingAttendanceRecognize: '/bidcompare/meeting-records/:id/attendance/recognize',
  meetingUnrecognizedFaces: '/bidcompare/meeting-records/:id/unrecognized-faces',
  meetingAttendance: '/bidcompare/meeting-records/:id/attendance',
  meetingQa: '/bidcompare/meeting-records/:id/qa',
  meetingQaAudio: '/bidcompare/meeting-records/:id/qa/audio',
  meetingQaAudioGet: '/bidcompare/meeting-records/qa/:qaId/audio',
  meetingRecording: '/bidcompare/meeting-records/:id/recording',
  meetingComplete: '/bidcompare/meeting-records/:id/complete',
  meetingReport: '/bidcompare/meeting-records/:id/report',
  meetingWorkers: '/bidcompare/meeting-workers',
  meetingWorkerFace: '/bidcompare/meeting-workers/:id/face',
  meetingWorkersRecognizeIdCard: '/bidcompare/meeting-workers/recognize-id-card',
  meetingProjects: '/bidcompare/meeting-projects',
  meetingProject: '/bidcompare/meeting-projects/:id',
  meetingProjectExtract: '/bidcompare/meeting-projects/:id/extract',
  meetingProjectSuggestName: '/bidcompare/meeting-projects/suggest-name',
  meetingProjectDocumentFile: '/bidcompare/meeting-projects/:id/documents/:docId/file',
  meetingProjectDocumentContent: '/bidcompare/meeting-projects/:id/documents/:docId/content',
} as const

export type UrlKey = keyof typeof urls
