<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.Gateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DredgeAI.Gateway.Application\DredgeAI.Gateway.Application.csproj" />
    <ProjectReference Include="..\..\src\DredgeAI.Gateway.HttpApi\DredgeAI.Gateway.HttpApi.csproj" />
    <ProjectReference Include="..\..\src\DredgeAI.Gateway.EntityFrameworkCore\DredgeAI.Gateway.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\DredgeAI.Gateway.Domain.Tests\DredgeAI.Gateway.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.extensibility.execution" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
