// <auto-generated />
using System;
using DredgeAI.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace DredgeAI.Migrations
{
    [DbContext(typeof(AuthServerDbContext))]
    partial class AuthServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Volo.Abp.OpenIddict.Applications.OpenIddictApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_application_type")
                        .HasComment("应用类型");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("f_client_id")
                        .HasComment("客户端Id");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("f_client_secret")
                        .HasComment("客户端密钥");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_client_type")
                        .HasComment("客户端类型");

                    b.Property<string>("ClientUri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("f_client_uri")
                        .HasComment("客户端Uri");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_consent_type")
                        .HasComment("同意类型");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_display_name")
                        .HasComment("显示名称");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("f_display_names")
                        .HasComment("国际化的显示名称");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<string>("FrontChannelLogoutUri")
                        .HasColumnType("text")
                        .HasColumnName("f_front_channel_logout_uri");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("f_json_web_key_set")
                        .HasComment("密钥");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("LogoUri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("f_logo_uri")
                        .HasComment("品牌图标");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("f_permissions")
                        .HasComment("权限集合");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("f_post_logout_redirect_uris")
                        .HasComment("退出登录后的回调");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("f_properties")
                        .HasComment("属性");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("f_redirect_uris")
                        .HasComment("登录后的回调");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("f_requirements")
                        .HasComment("必须启用的资源");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("f_settings")
                        .HasComment("设置");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("tab_openid_dict_applications", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.OpenIddict.Authorizations.OpenIddictAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_application_id")
                        .HasComment("所属应用Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_date")
                        .HasComment("创建时间（UTC）");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("f_properties")
                        .HasComment("属性");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("f_scopes")
                        .HasComment("授权范围");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_status")
                        .HasComment("状态");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("f_subject")
                        .HasComment("主题");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_type")
                        .HasComment("类型");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("tab_openid_dict_authorizations", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.OpenIddict.Scopes.OpenIddictScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_description")
                        .HasComment("描述");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("f_descriptions")
                        .HasComment("描述(国际化)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_display_name")
                        .HasComment("显示名称");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("f_display_names")
                        .HasComment("显示名称(国际化)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("f_name")
                        .HasComment("范围名称");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("f_properties")
                        .HasComment("属性");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("f_resources")
                        .HasComment("资源");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("tab_openid_dict_scopes", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.OpenIddict.Tokens.OpenIddictToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_application_id")
                        .HasComment("应用Id");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_authorization_id")
                        .HasComment("授权Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_date")
                        .HasComment("创建时间（UTC）");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_expiration_date")
                        .HasComment("过期时间（UTC）");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("f_payload")
                        .HasComment("票据内容");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("f_properties")
                        .HasComment("属性");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_redemption_date")
                        .HasComment("赎回时间");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("f_reference_id")
                        .HasComment("关联Id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_status")
                        .HasComment("状态");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("f_subject")
                        .HasComment("主题");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("f_type")
                        .HasComment("类型");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("tab_openid_dict_tokens", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.OpenIddict.Authorizations.OpenIddictAuthorization", b =>
                {
                    b.HasOne("Volo.Abp.OpenIddict.Applications.OpenIddictApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("Volo.Abp.OpenIddict.Tokens.OpenIddictToken", b =>
                {
                    b.HasOne("Volo.Abp.OpenIddict.Applications.OpenIddictApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Volo.Abp.OpenIddict.Authorizations.OpenIddictAuthorization", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
