import type { AppManifest } from '@shared/core/types/application'

/**
 * user-web 应用清单：声明所有用户端应用的路由/组件/权限元数据。
 * 路由表由 manifest 数组动态生成，admin 发布状态变更可热更新此清单。
 */
export const userAppManifests: AppManifest[] = [
  {
    id: 'dashboard',
    route: '/dashboard',
    name: 'UserDashboard',
    title: '工作台',
    icon: 'DashboardOutlined',
    component: () => import('@/views/dashboard/index.vue'),
    defaultVisible: true,
    category: '通用',
  },
  {
    id: 'standard-query',
    route: '/standard-query',
    name: 'StandardQuery',
    title: '标准查询',
    icon: 'FileSearchOutlined',
    component: () => import('@/views/standards/index.vue'),
    defaultVisible: true,
    category: '通用',
  },
  {
    id: 'ai-bid',
    route: '/ai-bid',
    name: 'AiBid',
    title: 'AI投标',
    icon: 'FileProtectOutlined',
    component: () => import('@/views/ai-bid/index.vue'),
    redirect: '/ai-bid/read',
    defaultVisible: true,
    category: '施工',
    children: [
      {
        id: 'ai-bid-read',
        route: '/read',
        name: 'AiBidRead',
        title: '读标',
        component: () => import('@/views/ai-bid/read/index.vue'),
      },
      {
        id: 'ai-bid-write',
        route: '/write',
        name: 'AiBidWrite',
        title: '写标',
        component: () => import('@/views/ai-bid/write/index.vue'),
      },
      {
        id: 'ai-bid-compare',
        route: '/compare',
        name: 'AiBidCompare',
        title: '比标',
        component: () => import('@/views/ai-bid/compare/index.vue'),
      },
      {
        id: 'ai-bid-clear',
        route: '/clear',
        name: 'AiBidClear',
        title: '清标',
        component: () => import('@/views/ai-bid/clear/index.vue'),
      },
    ],
  },
  {
    id: 'profile',
    route: '/profile',
    name: 'Profile',
    title: '个人中心',
    icon: 'UserOutlined',
    component: () => import('@/views/profile/index.vue'),
    category: '通用',
  },
  {
    id: 'api',
    route: '/api',
    name: 'ApiManage',
    title: 'API 管理',
    icon: 'ApiOutlined',
    component: () => import('@/views/api/index.vue'),
    category: '通用',
  },
  {
    id: 'ai-video',
    route: '/ai-video',
    name: 'AiVideo',
    title: 'AI视频',
    icon: 'VideoCameraOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    defaultVisible: true,
    category: '通用',
  },
  {
    id: 'ai-dubbing',
    route: '/ai-dubbing',
    name: 'AiDubbing',
    title: 'AI配音',
    icon: 'CustomerServiceOutlined',
    component: () => import('@/views/dubbing/index.vue'),
    defaultVisible: true,
    category: '通用',
  },
  {
    id: 'design-experience',
    route: '/design-experience',
    name: 'DesignExperience',
    title: '设计经验',
    icon: 'BulbOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    category: '设计',
  },
  {
    id: 'construction-experience',
    route: '/construction-experience',
    name: 'ConstructionExperience',
    title: '施工经验',
    icon: 'ToolOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    category: '施工',
  },
  {
    id: 'construction-review',
    route: '/construction-review',
    name: 'ConstructionReview',
    title: '施组审核',
    icon: 'ExperimentOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    category: '施工',
  },
  {
    id: 'dredge-efficiency',
    route: '/dredge-efficiency',
    name: 'DredgeEfficiency',
    title: '耙吸效率',
    icon: 'RadarChartOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    defaultVisible: true,
    category: '施工',
  },
  {
    id: 'intelligence-dredge',
    route: '/intelligence/dredge',
    name: 'IntelligenceDredge',
    title: '疏浚情报',
    icon: 'BookOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    defaultVisible: true,
    category: '经营',
  },
  {
    id: 'intelligence-tech',
    route: '/intelligence/tech',
    name: 'IntelligenceTech',
    title: '科技情报',
    icon: 'AppstoreOutlined',
    component: () => import('@/views/placeholder/PlaceholderView.vue'),
    defaultVisible: true,
    category: '经营',
  },
]
