// <auto-generated />
using System;
using DredgeAI.Gateway.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace DredgeAI.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DredgeAI.Gateway.Proxying.ProxyCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_cluster_id")
                        .HasComment("YARP 集群 ID，全局唯一");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("DestinationsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_destinations_json")
                        .HasComment("目的地字典 JSON（destinationId → 下游地址）");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("tab_proxy_cluster", (string)null);
                });

            modelBuilder.Entity("DredgeAI.Gateway.Proxying.ProxyRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("AuthorizationPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("f_authorization_policy")
                        .HasComment("授权策略（YARP 内置字面量 anonymous 或 default）");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_cluster_id")
                        .HasComment("引用的集群 ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("f_is_enabled")
                        .HasComment("是否启用；禁用的路由不进 YARP 快照");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("MatchHostsJson")
                        .HasColumnType("text")
                        .HasColumnName("f_match_hosts_json")
                        .HasComment("Host 匹配列表 JSON 数组，null 表示不限制");

                    b.Property<string>("MatchMethodsJson")
                        .HasColumnType("text")
                        .HasColumnName("f_match_methods_json")
                        .HasComment("HTTP 方法匹配列表 JSON 数组，null 表示不限制");

                    b.Property<string>("MatchPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_match_path")
                        .HasComment("路径匹配模式，如 /api/compare/{**catch-all}");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("f_order")
                        .HasComment("路由匹配优先级（值越小越优先）");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_route_id")
                        .HasComment("YARP 路由 ID，全局唯一");

                    b.HasKey("Id");

                    b.HasIndex("RouteId")
                        .IsUnique();

                    b.ToTable("tab_proxy_route", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
