// <auto-generated />
using System;
using DredgeAI.Gateway.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace DredgeAI.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DredgeAI.Gateway.Proxying.ProxyCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_cluster_id")
                        .HasComment("YARP 集群 ID，全局唯一");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_config_json")
                        .HasComment("完整 YARP ClusterConfig JSON（camelCase）");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_description")
                        .HasComment("集群描述");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("f_is_enabled")
                        .HasComment("是否启用；禁用的集群及其路由不进 YARP 快照");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("tab_proxy_cluster", (string)null);
                });

            modelBuilder.Entity("DredgeAI.Gateway.Proxying.ProxyRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_cluster_id")
                        .HasComment("引用的集群 ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_config_json")
                        .HasComment("完整 YARP RouteConfig JSON（camelCase）");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("f_description")
                        .HasComment("路由描述");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("f_is_enabled")
                        .HasComment("是否启用；禁用的路由不进 YARP 快照");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("f_order")
                        .HasComment("路由匹配优先级（值越小越优先）");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_route_id")
                        .HasComment("YARP 路由 ID，全局唯一");

                    b.HasKey("Id");

                    b.HasIndex("RouteId")
                        .IsUnique();

                    b.ToTable("tab_proxy_route", (string)null);
                });

            modelBuilder.Entity("DredgeAI.Gateway.RateLimiting.RateLimitPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("f_id")
                        .HasComment("主键Id");

                    b.Property<int>("Algorithm")
                        .HasColumnType("integer")
                        .HasColumnName("f_algorithm")
                        .HasComment("限流算法：0=固定窗口，1=滑动窗口，2=令牌桶");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("f_concurrency_stamp")
                        .HasComment("并发标识");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_creation_time")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_creator_id")
                        .HasComment("创建人ID");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_deleter_id")
                        .HasComment("删除者ID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_deletion_time")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_extra_properties")
                        .HasComment("拓展字段");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("f_is_deleted")
                        .HasComment("是否删除 0.否 1.是");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("f_is_enabled")
                        .HasComment("是否启用；禁用的策略不参与限流解析");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("f_last_modification_time")
                        .HasComment("修改时间");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_last_modifier_id")
                        .HasComment("修改者ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_name")
                        .HasComment("显示名，全局唯一");

                    b.Property<int?>("PermitLimit")
                        .HasColumnType("integer")
                        .HasColumnName("f_permit_limit")
                        .HasComment("窗口内允许的请求数（Fixed/Sliding 必填）");

                    b.Property<int>("QueueLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("f_queue_limit")
                        .HasComment("排队上限（>=0，默认 0 不排队）");

                    b.Property<int?>("ReplenishmentPeriodSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("f_replenishment_period_seconds")
                        .HasComment("令牌补充周期秒数（TokenBucket 必填）");

                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("f_route_id")
                        .HasComment("目标路由 ID（Scope=Route 时必填）");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("f_scope")
                        .HasComment("作用域：0=全局，1=路由级");

                    b.Property<int?>("SegmentsPerWindow")
                        .HasColumnType("integer")
                        .HasColumnName("f_segments_per_window")
                        .HasComment("滑动窗口分段数（Sliding 必填）");

                    b.Property<int?>("TokenLimit")
                        .HasColumnType("integer")
                        .HasColumnName("f_token_limit")
                        .HasComment("令牌桶容量（TokenBucket 必填）");

                    b.Property<int?>("TokensPerPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("f_tokens_per_period")
                        .HasComment("每周期补充令牌数（TokenBucket 必填）");

                    b.Property<int?>("WindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("f_window_seconds")
                        .HasComment("窗口时长秒数（Fixed/Sliding 必填）");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("f_is_deleted = false");

                    b.HasIndex("Scope", "RouteId");

                    b.ToTable("tab_rate_limit_policy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
