<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.Gateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DredgeAI.Gateway.Domain\DredgeAI.Gateway.Domain.csproj" />
    <ProjectReference Include="..\DredgeAI.Gateway.Application.Contracts\DredgeAI.Gateway.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

</Project>
