<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DredgeAI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Shiw.File.HttpApi" />
      <PackageReference Include="Shiw.File.Web" />
      <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
      <PackageReference Include="Volo.Abp.Identity.HttpApi" />
      <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" />
      <PackageReference Include="Volo.Abp.TenantManagement.HttpApi" />
      <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" />
      <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" />
      <PackageReference Include="Volo.Abp.Account.HttpApi" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DredgeAI.Base.Application.Contracts\DredgeAI.Base.Application.Contracts.csproj" />
    </ItemGroup>

</Project>
