<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DredgeAI.BidCompare</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DredgeAI.BidCompare.Domain\DredgeAI.BidCompare.Domain.csproj" />
    <ProjectReference Include="..\DredgeAI.BidCompare.TestBase\DredgeAI.BidCompare.TestBase.csproj" />
  </ItemGroup>

</Project>
